{% set name = "backports.strenum" %}
{% set version = "1.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/backports_strenum-{{ version }}.tar.gz
  sha256: 77c52407342898497714f0596e86188bb7084f89063226f4ba66863482f42414

build:
  noarch: python
  {% if build_type == 'regular' %}
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  {% endif %}
  number: 2

requirements:
  host:
    {% if build_type == 'regular' %}
    - python >=3.8,<3.11
    - backports
    - poetry-core
    - pip
    {% endif %}
  run:
    {% if build_type == 'regular' %}
    - python >=3.8.6,<3.11
    - backports
    {% else %}
    - python >=3.12
    {% endif %}

test:
  {% if build_type == 'regular' %}
  imports:
    - backports.strenum
  requires:
    - pip
  commands:
    - pip check
  {% else %}
  commands:
    - python -c "from enum import StrEnum"
  {% endif %}

about:
  home: https://github.com/clbarnes/backports.strenum
  summary: Base class for creating enumerated constants that are also subclasses of str
  license: PSF-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - tadeu
